  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/${DB_NAME:todo_db}
      username: onebase
      password:
    flyway:
      baseline-on-migrate: true
      url: jdbc:postgresql://localhost:5432/${DB_NAME:todo_db}
      user: onebase
      password: